---
name: xchem-align
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=21.1.1
  - openbabel=3.1.1
  - rdkit=2022.09.5
  - pandas=1.5.3
  - pyyaml=6.0
  - pip:
    - im-standardize-molecule==0.1.0
